### ISSUE TITLE
AsmSearchBox wrong url

### ISSUE THREAD

**Issue by matjazpotocnik** [baumrock/RockAdminTweaks#17]
I get this if I enable "AsmSearchBox - Add search box to ASM Select dropdowns"
![image](https://github.com/baumrock/RockAdminTweaks/assets/7663992/fe210ed0-81ad-4279-be3e-743c3ad51305)

**Comment by BernhardBaumrock** [comment]
Works well for me - maybe a windows issue? Can you please debug that on your own? And can you share the correct path of your asset and the one the module is trying to load?

**Comment by matjazpotocnik** [comment]
In pathToUrl() add: 

 ```
if (DIRECTORY_SEPARATOR != '/') {
       $path = str_replace(DIRECTORY_SEPARATOR, '/', $path);
  }
```

**Comment by BernhardBaumrock** [comment]
Fixed, thx!
