### ISSUE TITLE
jQuery.fn.select() event shorthand is deprecated

### ISSUE THREAD

**Issue by matjazpotocnik** [baumrock/RockAdminTweaks#2]
Instead of .select(), use [.trigger( "select" )](https://api.jquery.com/select/#trigger2).

**Comment by BernhardBaumrock** [comment]
Thx. Could you please provide more context and details?

**Comment by matjazpotocnik** [comment]
It's in CopyFieldNames.js:

```
$(document).ready(function () {
  // Copy a string to the clipboard
  function copyToClipboard(string) {
    const $temp = $('<input type="text" value="' + string + '">');
    $("body").append($temp);
    $temp.select();
    document.execCommand("copy");
    $temp.remove();
  }
```
Also, in the provided link https://processwire.com/talk/topic/29071-using-javascript-to-copy-page-ids-from-page-list-and-field-nameslabels-from-inputfields/ Robin is using alt, while you are using shift modifier. I had to look at the source to determine why alt wasn't working for me. I know docs are coming...

**Comment by BernhardBaumrock** [comment]
But isn't that just using the JS select method? https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

**Comment by matjazpotocnik** [comment]
$temp is jQuery object

**Comment by BernhardBaumrock** [comment]
I know, but I think it uses the JS select(). Could you please provide step by step instructions to reproduce the issue and tell me how I can see that the issue exists?

**Comment by matjazpotocnik** [comment]
Open dev tools :-)

![image](https://github.com/baumrock/RockAdminTweaks/assets/7663992/10db718a-0a19-43d0-9437-1d6606a9f09c)

And in config.php add `$config->debug = 'dev';`

**Comment by BernhardBaumrock** [comment]
Thx, should be fixed now!
