### ISSUE TITLE
ShowExtraActions trigger doesn't work

### ISSUE THREAD

**Issue by matjazpotocnik** [baumrock/RockAdminTweaks#3]
This line in ShowExtraActions.js

`$(document).on("hover", ".PageListItem", function () {`

does not work for me. I had to change it to 

`$(document).on("mouseover", ".PageListItem", function () {`

**Comment by BernhardBaumrock** [comment]
Thx. Which browser?

**Comment by matjazpotocnik** [comment]
Edge
